In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

# 张量

In [24]:
a = tf.constant(2, name='a', dtype=tf.uint8) #help(tf.constant)
b = tf.constant(3, name='b', dtype=tf.uint8) #help(tf.constant)
a.numpy() #取值
a.shape
a.get_shape()

TensorShape([])

In [9]:
a + b # 2.0 可以直接+-*/

<tf.Tensor: shape=(), dtype=uint8, numpy=5>

# 变量

In [40]:
s = tf.Variable(23, name='s', dtype=tf.uint8)
m = tf.Variable([[0,1],[1,2],[2,3]], name='matrix', dtype=tf.float32)
w = tf.Variable(tf.zeros([10,11]))

# 查看模型所有变量 model.variables

In [14]:
class MyModule(tf.Module):
    def __init__(self):
        self.v0 = tf.Variable(1.0)
        self.vs = [tf.Variable(x) for x in range(10)]
        
m = MyModule()
m.variables

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=8>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>)

# tf.data

In [17]:
dataset = tf.data.Dataset.from_tensors([1,2,3,4,5])
for element in dataset:
  print(element.numpy())
  it = iter(dataset)
print(next(it).numpy())


[1 2 3 4 5]
[1 2 3 4 5]


In [25]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5])
for element in dataset:
  print(element.numpy())
it = iter(dataset)
print(next(it).numpy())

1
2
3
4
5
1


In [46]:
features = tf.data.Dataset.from_tensor_slices([1,2,3,4,5])
labels = tf.data.Dataset.from_tensor_slices([6,7,8,9,10])
dataset = tf.data.Dataset.zip((features,labels))
for element in dataset:
  print(element)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=6>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=7>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=8>)
(<tf.Tensor: shape=(), dtype=int32, numpy=4>, <tf.Tensor: shape=(), dtype=int32, numpy=9>)
(<tf.Tensor: shape=(), dtype=int32, numpy=5>, <tf.Tensor: shape=(), dtype=int32, numpy=10>)


In [48]:
inc_dataset = tf.data.Dataset.range(100)   
dec_dataset = tf.data.Dataset.range(0, -100, -1) 
# 数据集合并
dataset = tf.data.Dataset.zip((inc_dataset, dec_dataset))


# 比如dataset有100个数据，那么batched_dataset为4组，每组25个数据，使用dataset.take(4),可以取出4个数据

batched_dataset = dataset.batch(8)  # 取前8个数据

for batch in batched_dataset.take(4):
  print([arr.numpy() for arr in batch])

[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 0, -1, -2, -3, -4, -5, -6, -7])]
[array([ 8,  9, 10, 11, 12, 13, 14, 15]), array([ -8,  -9, -10, -11, -12, -13, -14, -15])]
[array([16, 17, 18, 19, 20, 21, 22, 23]), array([-16, -17, -18, -19, -20, -21, -22, -23])]
[array([24, 25, 26, 27, 28, 29, 30, 31]), array([-24, -25, -26, -27, -28, -29, -30, -31])]


In [55]:
# 随机选取  buffer_size 杂乱程度 
shuffle_dataset = dataset.shuffle(buffer_size=11)
for element in shuffle_dataset.take(20):
  print(element)
  

(<tf.Tensor: shape=(), dtype=int64, numpy=4>, <tf.Tensor: shape=(), dtype=int64, numpy=-4>)
(<tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=-1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=7>, <tf.Tensor: shape=(), dtype=int64, numpy=-7>)
(<tf.Tensor: shape=(), dtype=int64, numpy=10>, <tf.Tensor: shape=(), dtype=int64, numpy=-10>)
(<tf.Tensor: shape=(), dtype=int64, numpy=14>, <tf.Tensor: shape=(), dtype=int64, numpy=-14>)
(<tf.Tensor: shape=(), dtype=int64, numpy=9>, <tf.Tensor: shape=(), dtype=int64, numpy=-9>)
(<tf.Tensor: shape=(), dtype=int64, numpy=12>, <tf.Tensor: shape=(), dtype=int64, numpy=-12>)
(<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=int64, numpy=15>, <tf.Tensor: shape=(), dtype=int64, numpy=-15>)
(<tf.Tensor: shape=(), dtype=int64, numpy=18>, <tf.Tensor: shape=(), dtype=int64, numpy=-18>)
(<tf.Tensor: shape=(), dtype=int64, numpy=5>, <tf.Tensor: shape=(), dty

In [ ]:
shuffle_dataset = dataset.shuffle(buffer_size=100)
for element in shuffle_dataset:
  print(element)
  